import type { Metadata } from "next";
import Image from "next/image";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import ReservationButton from "@/components/ReservationButton";
import { siteConfig } from "@/lib/site";

export const metadata: Metadata = { title: "Özel Davetler ve Etkinlikler", description: "Ember'da özel kutlamalar, şef masası ve gün batımı etkinlikleri.", alternates: { canonical: "/tr/private-dining", languages: { "en-US": "/private-dining", "tr-TR": "/tr/private-dining" } } };
const experiences = [["Şef masası", "10 kişiye kadar", "Açık mutfağın ön sırasında, size özel hazırlanan bir tadım menüsü."], ["Özel salon", "24 kişiye kadar", "Kutlamalar, lansmanlar ve uzun masa yemekleri için samimi bir salon."], ["Tüm restoran", "80 kişiye kadar", "Misafirleriniz ve etkinliğiniz için baştan sona tasarlanan bir Ember akşamı."]] as const;

export default function TurkishPrivateDiningPage() {
  return <main id="main-content" lang="tr" className="bg-[#f7eadf] text-[#261419] page-enter"><Navbar /><section className="relative flex min-h-[78svh] items-end px-5 pb-16 pt-36 text-white sm:px-8 lg:px-12"><Image src="/images/interior-evening.jpg" alt="Özel bir akşam için hazırlanan Ember salonu" fill priority sizes="100vw" className="object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#1b0b12] via-[#1b0b12]/45 to-[#1b0b12]/30" /><div className="relative z-10 mx-auto w-full max-w-[1440px]"><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#ffb37b]">Özel davetler</p><h1 className="mt-6 max-w-6xl font-serif text-[clamp(4.5rem,10vw,9rem)] leading-[0.76] tracking-[-0.05em]">Sizin davetiniz,<br /><span className="italic text-[#ff9a62]">bizim soframız.</span></h1></div></section><section className="mx-auto max-w-[1200px] px-5 py-24 sm:px-8 lg:py-36"><div className="grid gap-6 md:grid-cols-3">{experiences.map(([title, capacity, text], index) => <article key={title} className="border border-[#261419]/18 p-7 sm:p-9"><span className="text-xs font-bold tracking-[0.2em] text-[#c84f30]">0{index + 1}</span><h2 className="mt-16 font-serif text-4xl">{title}</h2><p className="mt-3 text-xs font-bold uppercase tracking-[0.14em] text-[#c84f30]">{capacity}</p><p className="mt-6 text-sm leading-7 text-[#6f5555]">{text}</p></article>)}</div></section><section className="grid bg-[#ff8652] lg:grid-cols-2"><div className="relative min-h-[32rem]"><Image src="/images/interior-red.jpg" alt="Özel etkinlik masa düzeni" fill sizes="50vw" className="object-cover" /></div><div className="flex items-center px-5 py-20 sm:px-12 lg:px-20"><div><p className="text-xs font-bold uppercase tracking-[0.25em]">Mevsimlik etkinlikler</p><h2 className="mt-6 font-serif text-6xl leading-[0.9] sm:text-7xl">Yalnızca bir gece.</h2><p className="mt-7 max-w-xl text-sm leading-7 text-[#5d3533]">Şarap üreticisi yemekleri, konuk şefler ve yaz sonu teras akşamları yıl boyunca takvimde yerini alıyor.</p><div className="mt-9 flex flex-wrap gap-3"><ReservationButton className="rounded-full bg-[#261419] px-7 py-4 text-xs font-bold uppercase tracking-[0.18em] text-white">Etkinlik planla</ReservationButton><a href={`mailto:${siteConfig.email}?subject=Ember%20hediye%20kartı`} className="rounded-full border border-[#261419]/30 px-7 py-4 text-xs font-bold uppercase tracking-[0.18em]">Hediye kartı al</a></div></div></div></section><Footer locale="tr" /></main>;
}
